### ISSUE TITLE
Agregar soporte para imágenes comprimidas con JPEG

### ISSUE THREAD

**Issue by mnamias** [FranFunes/PETfectior_Client#24]
Al enviar imágenes comprimidas con JPEG-LS (lossless) falla la decodificación y el cliente no lee las imágenes.

RuntimeError('The following handlers are available to decode the pixel data however they are missing required dependencies: GDCM (req. GDCM), JPEG-LS (req. CharPyLS), pylibjpeg (req. )')

**Comment by FranFunes** [comment]
@mnamias no pude reproducir el error. Probé enviar una serie desde el PACS y la procesó sin problemas. ¿Te acordás qué estudio era el que mandaste a procesar?

**Comment by FranFunes** [comment]
Modifiqué el receptor DICOM para que no acepte DICOMs comprimidos, sólo las Transfer Syntax típicas, incluídas en
pynetdicom._globals como DEFAULT_TRANSFER_SYNTAXES.
