### ISSUE TITLE
Postproceso del lado del cliente: configuración del PET que generó las imágenes

### ISSUE THREAD

**Issue by mnamias** [FranFunes/PETfectior_Client#25]
Actualmente el cliente permite configurar post-procesos (filtrado gaussiano) para poder armonizar las imágenes según preferencia del usuario. Sin embargo, si el usuario cuenta con más de un modelo de PET en su servicio, estos parámetros no serían válidos. Por lo tanto, en la solapa de configuración deberían quedar los siguientes campos:

Post processing configuration:

PET_Modelname    Series description   Naming mode    Series Number   FWHM  Enabled

PET_Modelname deberá coincidir con el contenido del campo DICOM Manufacturer Model Name. El post-proceso sólo se deberá aplicar a las imágenes generadas en ese modelo y no otro.

Por otro lado, sería deseable que la lista de modelos disponibles se actualice automáticamente al recibir imágenes DICOM de nuevos equipos.

**Comment by FranFunes** [comment]
Solucionado en el commit 0469457
