### ISSUE TITLE
Error al renombrar series con sufijo

### ISSUE THREAD

**Issue by mnamias** [FranFunes/PETfectior_Client#28]
Al seleccionar la opción Naming mode = Replace en la pestaña Config, no se agrega el sufijo correctamente. La función "Replace" sí funciona bien.

![image](https://github.com/FranFunes/PETfectior_Client/assets/38704586/d873a16a-7711-4f3c-ba0d-d99f598ac2c9)

![image](https://github.com/FranFunes/PETfectior_Client/assets/38704586/71cd6996-6901-426f-8fdb-b837e58ec5b9)

**Comment by FranFunes** [comment]
Se solucionó al recrear las configuraciones de post-proceso en el cliente.
