### ISSUE TITLE
Agregar información en los datos transmitidos

### ISSUE THREAD

**Issue by mnamias** [FranFunes/PETfectior_Client#33]
En el archivo JSON de metadatos enviados al servidor dentro del archivo ZIP, incluir:

StudyInstanceUID
SeriesInstanceUID
SeriesNumber
StudyDate
Dosis de radiofármaco inyectado
Hora de inyección
Hora de imagen
Peso y altura del paciente
Edad del paciente

**Comment by FranFunes** [comment]
Agregar además toda la información que se pueda extraer del radiofármaco.

**Comment by FranFunes** [comment]
Resuelto. Ejemplo de metadata.json enviado al servidor:

{
  "client_id": "SQLite",
  "task_id": "202407241540264304",
  "recon_settings": {
    "00080070": {
      "Value": [
        "GE MEDICAL SYSTEMS"
      ],
      "vr": "LO"
    },
    "00081090": {
      "Value": [
        "Discovery 710"
      ],
      "vr": "LO"
    },
    "000910B2": {
      "Value": [
        2
      ],
      "vr": "SS"
    },
    "000910B3": {
      "Value": [
        18
      ],
      "vr": "SS"
    },
    "000910BA": {
      "Value": [
        1
      ],
      "vr": "SS"
    },
    "000910BB": {
      "Value": [
        5.199999809265137
      ],
      "vr": "FL"
    },
    "000910DC": {
      "Value": [
        4.0
      ],
      "vr": "FL"
    },
    "00101030": {
      "Value": [
        45.0
      ],
      "vr": "DS"
    },
    "00180050": {
      "Value": [
        3.27
      ],
      "vr": "DS"
    },
    "00180088": {
      "Value": [
        3.270000175889478
      ],
      "vr": "DS"
    },
    "00181242": {
      "Value": [
        120000
      ],
      "vr": "IS"
    },
    "00280030": {
      "Value": [
        3.6458332538605,
        3.6458332538605
      ],
      "vr": "DS"
    },
    "00540016": {
      "Value": [
        {
          "00180031": {
            "Value": [
              "FDG -- fluorodeoxyglucose"
            ],
            "vr": "LO"
          },
          "00181071": {
            "Value": [
              1.0
            ],
            "vr": "DS"
          },
          "00181072": {
            "Value": [
              "164100.00"
            ],
            "vr": "TM"
          },
          "00181073": {
            "Value": [
              "164200.00"
            ],
            "vr": "TM"
          },
          "00181074": {
            "Value": [
              150372752.0
            ],
            "vr": "DS"
          },
          "00181075": {
            "Value": [
              6586.2001953125
            ],
            "vr": "DS"
          },
          "00181076": {
            "Value": [
              0.96700000762939
            ],
            "vr": "DS"
          },
          "00181078": {
            "Value": [
              "20240618164100.00"
            ],
            "vr": "DT"
          },
          "00181079": {
            "Value": [
              "20240618164200.00"
            ],
            "vr": "DT"
          },
          "00540300": {
            "Value": [
              {
                "00080100": {
                  "Value": [
                    "C-111A1"
                  ],
                  "vr": "SH"
                },
                "00080102": {
                  "Value": [
                    "SRT"
                  ],
                  "vr": "SH"
                },
                "00080104": {
                  "Value": [
                    "^18^Fluorine"
                  ],
                  "vr": "LO"
                }
              }
            ],
            "vr": "SQ"
          },
          "00540304": {
            "Value": [
              {
                "00080100": {
                  "Value": [
                    "C-B1031"
                  ],
                  "vr": "SH"
                },
                "00080102": {
                  "Value": [
                    "SRT"
                  ],
                  "vr": "SH"
                },
                "00080104": {
                  "Value": [
                    "Fluorodeoxyglucose F^18^"
                  ],
                  "vr": "LO"
                }
              }
            ],
            "vr": "SQ"
          }
        }
      ],
      "vr": "SQ"
    },
    "00541103": {
      "Value": [
        "VPFXS"
      ],
      "vr": "LO"
    }
  },
  "PatientWeight": 45.0,
  "PatientSize": 1.45,
  "PatientAge": "010Y",
  "StudyInstanceUID": "1.2.840.113619.2.290.3.1460327308.395.1718711696.274",
  "SeriesInstanceUID": "1.2.840.113619.2.290.3.1460327308.395.1718711696.712",
  "SeriesNumber": 13,
  "SeriesDate": "20240618",
  "SeriesTime": "173510",
  "sha256": "3baebe318f4d24ae48fcdf2e53cb53fe2a865273f362d113e951defce1fe5045"
}
