### ISSUE TITLE
Actualizar API pedido de procesamiento

### ISSUE THREAD

**Issue by mnamias** [FranFunes/PETfectior_Client#38]
Agregar estos campos durante el pedido de procesamiento:

task_id BIGINT,
  file_name VARCHAR(255),
  client_id VARCHAR(255),
  start_time DATETIME,
  success_perc INT,
  end_time DATETIME,
  StudyInstanceUID VARCHAR(255),
  SeriesInstanceUID VARCHAR(255),
  StudyDate DATETIME,
  SeriesTime DATETIME,
  radiopharmaceutical_id VARCHAR(150),
  radiopharmaceutical_dose DECIMAL(10,2),
  radiopharmaceutical_start DATETIME,  
  weight INT(10),
  height INT(10),
  age INT(10),

**Comment by FranFunes** [comment]
Resuelto en https://github.com/FranFunes/PETfectior_Client/pull/47
