### ISSUE TITLE
Loguear los datos del estudio a procesar en el Validador

### ISSUE THREAD

**Issue by mnamias** [FranFunes/PETfectior_Client#42]
En el proceso validador, loguear los datos que van en el JSON en caso de ser aceptado (parámetros de recon y radiofármaco sobre todo). Esto es para facilitar el proceso de configuración de nuevos clientes / radiofármacos / modelos de procesamiento.

**Comment by FranFunes** [comment]
Resuelto en https://github.com/FranFunes/PETfectior_Client/pull/48
