### ISSUE TITLE
Actualizar la configuración de post-filtros

### ISSUE THREAD

**Issue by mnamias** [FranFunes/PETfectior_Client#43]
Evaluar la posibilidad de que en el menú "Edit postfilter settings", así como se puede seleccionar un PET de origen, se pueda seleccionar a qué radiofármaco aplica la regla.

Ej: tenemos un modelo entrenado para el 710, con 2i18s.  Si es un FDG, entonces el post-filtro debería ser 4.5 mm, Si es DOTATE, 7 mm.

**Comment by FranFunes** [comment]
Resuelto en https://github.com/FranFunes/PETfectior_Client/pull/49
