### ISSUE TITLE
La ruta de procesamiento no es tomada de la pantalla de configuración (parece hardcodeada)

### ISSUE THREAD

**Issue by mnamias** [FranFunes/PETfectior_Client#52]
Configuré una ruta de la carpeta compartida inexistente a propósito. El procesamiento funcionó igual (escribe el .zip en la carpeta compartida en el NAS). La falla persiste al detener los servicios y reiniciarlos

![image](https://github.com/user-attachments/assets/9985fffb-ed3f-4d2c-83e5-8e4f85b55551)

**Comment by mnamias** [comment]
Sí, parece estar hardcodeada:

![image](https://github.com/user-attachments/assets/c63cb391-6848-45ba-8ec1-e2ee37e9ac12)

**Comment by FranFunes** [comment]
@mnamias  La ruta a la carpeta montada en el NAS es una variable de entorno. El mount se  hace cuando la aplicación levanta, usando esa variable de entorno, y fuera de la aplicación principal. Creo que no debería estar visible al usuario final (no hay ninguna razón por la que debería modificar eso, dado que es una configuración que se maneja del lado del servidor). Si eventualmente se modificara la ruta (esto no debería pasar seguido) se me ocurren dos posibilidades para manejarlo:
- Publicar un update de la aplicación cliente, con la variable de entorno corregida. La aplicación cliente de cada usuario dejaría de funcionar hasta que la actualice. La aplicación cliente no cambiaría en nada (el mount se hace al iniciar la aplicación, tomando la ruta de una variable de entorno).
- Que el server le comunique de alguna forma la ruta al cliente (p.ej. durante el check_model), y el cliente escriba en esa ruta.

Si decidimos ir por la segunda opción, hay que modificar la lógica del mount en el cliente: cada vez que va a validar una tarea, debería:

- Pedirle al servidor la ruta compartida (p.ej. cuando llama a check_model).
- Verificar que no haya cambiado.
- Si cambió, desmontar la carpeta de red existente y montar la nueva.

Todo esto sería transparente al usuario, aunque podemos agregar un punto de monitoreo que muestre si el mount fue exitoso o falló, y en qué punto está montada la carpeta compartida (para simplificar el soporte en el futuro).

**Comment by FranFunes** [comment]
Resuelto en https://github.com/FranFunes/PETfectior_Client/commit/546f99f73f190fe1aa2f8962c4de2165057eac3a y https://github.com/FranFunes/PETfectior_Client/commit/43c61f5a84f0026ebac68f258a393a25e28e35f7
